### ISSUE TITLE
Can't log in when using custom domain

### ISSUE THREAD

**Issue by jorgeavaldez** [render-examples/open-web-analytics#2]
After deploying and running through the installation, I learned that Chrome doesn't allow login due to some samesite origin issues?

But after setting a custom domain, it looks like it continues to redirect me to the render deployment url.

After taking a look at the config file, it seems it's hardcoded to pull RENDER_EXTERNAL_URL: https://github.com/render-examples/open-web-analytics/blob/master/owa-config.php#L62

I'm not sure if render currently has something to allow us to pull the configured domain name, but for now I'm going to attempt to deploy a fork of this with the owa-config patched to read from a different environment variable.

**Comment by wendorf** [comment]
Hi @jorgeavaldez, thanks for the report! I've just merged #3 which should address the issue for you.

**Comment by jorgeavaldez** [comment]
Thank you! Much appreciated!
